server:
  port: 6660
logging:
  level:
    root: info

security:
  oauth2:
    resource:
      filter-order: 3 # 当OAuth2server 和 ResourceServer同时存在是需要考虑这个优先级的问题

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
    register-with-eureka: false

spring:
  application:
    name: oauth2-service